# Generated by Django 6.0.3 on 2026-05-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotransformjob',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='audiotransformjob',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='audiotransformjob',
            name='key',
        ),
    ]
