# Generated by Django 6.0.3 on 2026-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0002_remove_audiotransformjob_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotransformjob',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
