# Generated by Django 6.0.3 on 2026-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0003_audiotransformjob_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotransformjob',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
