# Generated by Django 6.0.3 on 2026-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0004_alter_audiotransformjob_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotransformjob',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
